name: 'Home Assistant helper: JQ'
description: 'GitHub action helper: JQ'
inputs:
  path:
    description: The relative dir path to where this should run
    required: false
    default: '.'
runs:
  using: "composite"
  steps: 
    - shell: bash
      env:
        INPUTS_PATH: ${{ inputs.path }}
        WORKSPACE: ${{ github.workspace }}
      run: |
        declare -a jsonfiles
        for jsonfile in $(find "$WORKSPACE/$INPUTS_PATH" -type f -name "*.json"); do
          echo "Linting: $jsonfile";
          cat "$jsonfile" | jq -e '.' >/dev/null;
        done;