name: 'Home Assistant helper: CAS'
description: 'GitHub action helper: CAS'
inputs:
  version:
    description: Codenotary CAS version
    required: false
    default: "v1.0.1"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        INPUTS_VERSION: ${{ inputs.version }}
      run: |
        mkdir -p "$ACTION_PATH/bin"
        curl -Lo "$ACTION_PATH/bin/cas" https://github.com/codenotary/cas/releases/download/$INPUTS_VERSION/cas-$INPUTS_VERSION-linux-amd64-static
        chmod a+x "$ACTION_PATH/bin/cas"
        echo "$ACTION_PATH/bin" >> "$GITHUB_PATH"
    - shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: |
        cp "$ACTION_PATH/cas-trusted-signing-pub-key" ~/.cas-trusted-signing-pub-key
